name: mobile_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0' # Saya sarankan rentang yang lebih umum untuk Dart SDK

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.0.0 # Mungkin perlu ^1.1.0 jika ada null safety issue
  lucide_icons: ^0.257.0 # Mungkin perlu versi terbaru jika ada isu
  cupertino_icons: ^1.0.8
  pie_chart: ^5.1.0
  flutter_native_splash: ^2.4.0 # Versi stabil sebelumnya, atau cek terbaru
  just_audio: ^0.9.36
  audioplayers: ^6.0.0
  # Untuk Database Lokal SQLite
  sqflite: ^2.3.3 # Atau versi terbaru
  path_provider: ^2.1.3 # Atau versi terbaru
  path: ^1.9.0 # Biasanya otomatis terinstal dengan sqflite
  get: ^4.6.5
  sp_util: ^2.0.3
  flutter_easyloading: ^3.0.5
  http: ^1.2.1
  provider: ^6.1.2 
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Coba turunkan versi lints jika ada masalah dengan SDK

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/